spring:
  application:
    name: metargraph
  data:
    mongodb:
      uuid-representation: standard
      authentication-database: admin
  graphql:
    graphiql:
      enabled: true
    websocket:
      path: /graphql
    schema:
      printer:
        enabled: true
  main:
    web-application-type: reactive

auth:
  jwt:
    expiration: "1h"
